### 회원가입
POST http://localhost:9090/api/auth/sign-up
Content-Type: application/json

{
  "email": "2@lol.com",
  "pwd": "12345678"
}

### 이메일 형식 맞지 않음
POST http://localhost:9090/api/auth/sign-up
Content-Type: application/json

{
"email": "1lol.com",
"pwd": "12345678"
}

### 비밀번호 형식 맞지 않음
POST http://localhost:9090/api/auth/sign-up
Content-Type: application/json

{
"email": "1@lol.com",
"pwd": "123"
}

### 비밀번호 맞지 않음
POST http://localhost:9090/api/auth/login
Content-Type: application/json

{
  "email": "1@lol.com",
  "pwd": "123477778"
}

### 로그인 성공
POST http://localhost:9090/api/auth/login
Content-Type: application/json

{
  "email": "1@lol.com",
  "pwd": "12345678"
}

### 유저 확인
GET http://localhost:9090/api/users/1
Content-Type: application/json
